-- ═════════════════════════════════════════════════════════════════
-- SECURITY: Revoke public access to internal/admin/dangerous functions
-- ═════════════════════════════════════════════════════════════════

-- Internal functions (_ prefix) — service_role only
REVOKE EXECUTE ON FUNCTION public._admin_has_active_session(_exclude_user uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._admin_log(_target uuid, _action text, _old jsonb, _new jsonb) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._admin_notify_others(_action text, _payload jsonb) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._admin_security_housekeeping() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._afk_forfeit_player(_slug text, _game_id uuid, _uid uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._app_settings_validate_trigger() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._apply_game_commission() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._assert_solo_bot_enabled() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._auto_advance_overdue_turns() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._auto_cancel_open_games() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._auto_resume_paused_games() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._chat_snapshot_sender() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._chess_apply_move(_game_id uuid, _fen_after text, _turn text, _san text, _uci text, _by_user uuid, _elapsed_ms integer, _mover_color text, _clear_draw_offer uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._chess_can_claim_draw(_game_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._chess_check_game_end(_game_id uuid, _fen_after text) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._chess_ephemeral_bot(_pseudo text) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._chess_gen_code() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._chess_halfmove_clock(_fen text) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._chess_has_mating_material(_fen text, _color text) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._chess_insufficient_material(_fen text) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._chess_payout(_game_id uuid, _winner uuid, _draw boolean) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._chess_position_key(_fen text) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._chess_settle(_id uuid, _winner uuid, _draw boolean, _reason text) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._chess_sync_fen_turn(_fen text, _turn text) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._debug_domino_tick(_game_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._domino_active_humans(_gid uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._domino_apply_turn_timer() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._domino_arm_bot_think(_game_id uuid, _slot integer, _state jsonb) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._domino_auto_draw(_game_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._domino_autoplay_bots(_game_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._domino_bot_pick_move(_state jsonb, _slot integer, _intel integer) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._domino_bot_step(_game_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._domino_deal(_n_players integer) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._domino_end_round(_game_id uuid, _winner_slot integer) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._domino_finalize(_game_id uuid, _winner_slot integer) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._domino_hand_pips(_hand jsonb) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._domino_init_state() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._domino_lock_game(_game_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._domino_lowest_pip_slot(_game_id uuid, _state jsonb) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._domino_next_playable_slot(_game_id uuid, _from_slot integer, _state jsonb) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._domino_next_round(_game_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._domino_normalize_board(_board jsonb) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._domino_place_first(_game_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._domino_play_as(_game_id uuid, _slot integer, _move jsonb) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._domino_playable_tiles(_state jsonb, _slot integer) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._domino_purge(_game_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._domino_required_starter_slot(_game_id uuid, _state jsonb) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._domino_slot_has_playable(_state jsonb, _slot integer) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._domino_start(_game_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._domino_turn_delay(_game_id uuid, _slot integer) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._domino_turn_state(_state jsonb, _turn_seconds integer) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._domino_visible(_game_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._end_bot_only_games() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._fanorona_apply_move(_game_id uuid, _slot integer, _move jsonb) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._fanorona_axis(_dr integer, _dc integer) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._fanorona_bot_pick_move(_game_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._fanorona_capture_lists(_board jsonb, _my integer, _from integer, _to integer) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._fanorona_capture_lists(_board jsonb, _my integer, _from integer, _to integer, _cols integer, _rows integer) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._fanorona_draw_refund(_game_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._fanorona_finalize(_game_id uuid, _winner_slot integer) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._fanorona_init_board() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._fanorona_init_board(_cols integer, _rows integer) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._fanorona_piece_can_capture(_board jsonb, _my integer, _idx integer, _visited jsonb, _last_axis text) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._fanorona_piece_can_capture(_board jsonb, _my integer, _idx integer, _visited jsonb, _last_axis text, _cols integer, _rows integer) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._fanorona_player_can_capture(_board jsonb, _my integer) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._fanorona_player_can_capture(_board jsonb, _my integer, _cols integer, _rows integer) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._fanorona_player_has_move(_board jsonb, _my integer) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._fanorona_player_has_move(_board jsonb, _my integer, _cols integer, _rows integer) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._fanorona_visible(_game_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._finance_tests_cleanup(_ids uuid[]) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._game_cfg(_slug text) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._game_resume_internal(_slug text, _game_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._game_visible(_game_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._gen_room_code() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._grant_admin_for_seed_emails() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._guard_balance_non_negative() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._is_game_participant(_game_id uuid, _user_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._is_valid_email(_raw text) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._is_valid_http_url(_raw text) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._is_valid_mg_phone(_raw text) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._log_admin_action(_action text, _target_type text, _target_id uuid, _payload jsonb) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._log_house_on_finish() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._ludo_active_humans(_game_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._ludo_advance_turn(_game_id uuid, _new_slot integer, _last_event text) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._ludo_auto_move(_game_id uuid, _slot integer) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._ludo_check_afk(_game_id uuid, _slot integer) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._ludo_check_game_over(_game_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._ludo_check_last_standing(_game_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._ludo_check_power_tile(st jsonb, _slot integer, _pawn_idx integer, _new_k integer, _start_idx integer) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._ludo_check_stalemate(_game_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._ludo_clear_shield(st jsonb, _slot integer) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._ludo_count_on_cell(st jsonb, _slot integer, _path_idx integer) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._ludo_ensure_state(_game_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._ludo_gen_power_tiles(_max_players integer) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._ludo_init_state(_max_players integer, _mode text) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._ludo_is_blocked(st jsonb, _moving_slot integer, _path_idx integer, _max_players integer) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._ludo_is_safe(_idx integer) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._ludo_log_state_change() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._ludo_movable_pawns(st jsonb, _slot integer, _dice integer) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._ludo_next_slot(_game_id uuid, _from integer, _max integer) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._ludo_playable_pawns(_pawns jsonb, _slot integer, _dice integer) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._ludo_purge(_game_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._ludo_push_move(_game_id uuid, _entry jsonb) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._ludo_relocate_power_tile(st jsonb, _old_cell integer) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._ludo_set_ready_deadline() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._ludo_start_for(_game_id uuid, _slot integer) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._ludo_start_idx(_slot integer) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._ludo_sync_turn_snapshot() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._mark_first_game() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._maybe_end_bot_only_domino(_game_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._maybe_end_bot_only_fanorona(_game_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._maybe_end_bot_only_ludo(_game_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._maybe_end_bot_only_poker(_game_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._maybe_end_bot_only_rami(_game_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._notify_deposit_created() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._petanque_distance(ax double precision, ay double precision, bx double precision, by_ double precision) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._petanque_end_round(_game_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._petanque_next_player(_game_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._petanque_settle(_game_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._petanque_simulate(p_throw_y double precision, p_angle double precision, p_power double precision, p_spin double precision, p_lob double precision) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._poker_apply_turn_timer() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._poker_award(_gid uuid, _winner uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._poker_bot_act(_gid uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._poker_hand_strength(hole integer[], community integer[]) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._prr_touch() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._rami_active_humans(_gid uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._rami_all_discards(_state jsonb) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._rami_autoplay_bots(_game_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._rami_check_win(_state jsonb, _key text) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._rami_check_win(_state jsonb, _uid uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._rami_discards_map(_state jsonb) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._rami_gen_code() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._rami_is_joker(_c integer, _mode text, _rj integer) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._rami_last_discarder(_state jsonb) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._rami_meld_type(_cards integer[], _mode text, _rj integer) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._rami_normalize_state(_state jsonb) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._rami_remove_one(_arr integer[], _v integer) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._rami_reshuffle(_state jsonb) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._rami_validate_meld(_cards integer[]) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._rami_visible(_game_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._referral_on_deposit() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._referral_on_phone_verified() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._referral_on_signup() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._referral_on_stake() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._set_chess_global_deadline() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._set_fanorona_global_deadline() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._set_turn_deadline() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._set_updated_at() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._skip_noop_update() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._sync_banned_flags() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._t_build_round(_tid uuid, _round integer, _ids uuid[]) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._t_draw_pools(_tid uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._t_finish(_tid uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._t_launch_match(_match_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._t_match_finish(_match_id uuid, _winner uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._t_notify(_entrant uuid, _title text, _body text, _link text) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._t_pool_rank(_pool_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._t_pool_recompute(_pool_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._t_sim_resolve(_tid uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._t_touch() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._tmatch_set_join_deadline() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._touch_shuffle_draft() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._tourn_assign_ludo_waves(_tid uuid, _round integer) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._tourn_launch_after_finish() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._tourn_launch_ludo_match(_match_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._tourn_ludo_active_count() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._tourn_ludo_limit() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._tourn_wave_for(_idx integer, _total integer, _limit integer) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._tpool_notify(_uids uuid[], _title text, _body text, _tid uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._tpool_touch() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._trg_afk_warning_non_ludo() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._trg_balance_audit() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._trg_check_achievements_on_win() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._trg_domino_participant_end_check() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._trg_fanorona_participant_end_check() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._trg_ludo_participant_end_check() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._trg_no_bot_money() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._trg_no_bot_tx() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._trg_poker_player_end_check() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._trg_pool_match_finished() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._trg_rami_participant_end_check() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._trg_third_place_auto_payout() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._trg_third_place_notify() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._trg_third_place_set_deadline() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._try_unlock_referral(_uid uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._update_player_stats_on_win() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public._validate_app_settings(_row app_settings) FROM anon, authenticated;

-- Dangerous/cron functions — service_role only
REVOKE EXECUTE ON FUNCTION public.auto_finish_abandoned_games() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.chess_auto_end(_game_id uuid, _winner uuid, _draw boolean) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.chess_auto_timeout(_game_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.chess_tick_all() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.cleanup_stale_games() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.cleanup_stale_open_games() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.credit_user_balance(_user_id uuid, _amount numeric, _type text, _ref_id uuid, _note text, _meta jsonb) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.debit_user_balance(_user_id uuid, _amount numeric, _type text, _ref_id uuid, _note text, _meta jsonb) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.domino_tick_all() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.fanorona_play_as_bot(_game_id uuid, _move jsonb) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.fanorona_tick_all() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.ludo_tick_all() FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.refund_game(_game_id uuid) FROM anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.tick_all_games() FROM anon, authenticated;

-- Admin functions — REVOKE from anon, keep authenticated (has is_admin() check)
REVOKE EXECUTE ON FUNCTION public.admin_activate_alias(p_alias_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_activate_persona(p_pseudo text, p_avatar_url text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_add_bot(_game_id uuid, _bot_name text, _intelligence integer, _win_bias integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_adjust_balance(_user_id uuid, _amount numeric, _note text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_advance_domino_round(_tid uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_align_balances() FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_announcement_create(_title text, _body text, _image_url text, _link text, _link_label text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_announcement_delete(_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_announcement_toggle(_id uuid, _active boolean) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_audit_unlogged_changes(_hours integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_auto_process_expired_matches(_tid uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_auto_start_ready_matches(_tid uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_banner_delete(_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_banner_upsert(_id uuid, _title text, _subtitle text, _image_url text, _button_text text, _button_link text, _bg_gradient text, _starts_at timestamp with time zone, _ends_at timestamp with time zone, _active boolean, _sort_order integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_broadcast_delete(_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_broadcast_send(_message text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_chat_mute(_user_id uuid, _minutes integer, _ban boolean, _reason text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_chat_unmute(_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_check_lockout(_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_close_expired_registrations() FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_create_community(_name text, _image_url text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_create_domino_tournament(_name text, _max_players integer, _stake numeric, _is_free boolean, _description text, _rewards_text text, _registration_opens_at timestamp with time zone, _registration_closes_at timestamp with time zone, _bye_strategy text, _move_timer_secs integer, _join_timeout_secs integer, _disconnect_grace_secs integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_create_session(_mfa_verified boolean, _approval_id uuid, _ip inet, _user_agent text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_dashboard_kpis() FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_dashboard_totals() FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_deactivate_persona() FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_delete_alias(p_alias_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_delete_community(_room_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_delete_game(_game_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_dm_send(_user_id uuid, _message text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_finance_kpi() FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_force_finish_game(_game_id uuid, _winner_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_force_match_result(_mid uuid, _winner_id uuid, _reason text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_forfeit_match_player(_mid uuid, _loser_id uuid, _reason text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_games_history(_limit integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_get_bot_config(_participant_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_get_forfeit_cron_info() FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_get_fraud_flags(_status text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_get_intervention_dashboard() FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_get_persona() FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_house_income(_since timestamp with time zone) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_join_game(_game_id uuid, _display_name text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_leaderboard_list(_period text, _limit integer, _slug text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_list_aliases() FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_list_all_active_sessions() FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_list_bug_reports(_status text, _limit integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_list_games() FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_list_my_sessions() FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_list_phone_requests() FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_list_users() FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_list_users_sorted(_sort text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_manual_payout(_uid uuid, _amount numeric, _reason text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_offer_delete(_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_offer_upsert(_id uuid, _title text, _description text, _image_url text, _link text, _expires_at timestamp with time zone, _active boolean) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_override_login(_reason text, _ip inet, _user_agent text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_override_match_winner(_mid uuid, _winner_id uuid, _reason text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_permanently_delete_user(_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_process_deposit(_id uuid, _approve boolean) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_process_withdrawal(_id uuid, _approve boolean) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_reconcile_balances() FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_record_login_attempt(_user_id uuid, _success boolean, _reason text, _ip inet, _ua text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_refund_game(_game_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_rename_bot(_participant_id uuid, _name text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_reply_support(_id uuid, _reply text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_request_login_approval(_ip inet, _user_agent text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_reset_all_terms() FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_resolve_claim(_cid uuid, _status text, _comment text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_resolve_fraud_flag(_flag_id uuid, _resolution text, _pay_anyway boolean) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_respond_login_approval(_request_id uuid, _decision text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_revoke_all_other_sessions() FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_revoke_any_session(_session_id uuid, _reason text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_revoke_session(_session_id uuid, _reason text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_save_alias(p_pseudo text, p_avatar_url text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_search_users(_q text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_season_close(_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_season_upsert(_id uuid, _name text, _starts_at timestamp with time zone, _ends_at timestamp with time zone, _reward_text text, _reward_amount numeric) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_send_email_otp() FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_set_daily_bonus(_enabled boolean, _amount_ar integer, _streak_bonus boolean) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_set_forfeit_cron_interval(_seconds integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_set_leaderboard_hidden(_user_id uuid, _hidden boolean) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_set_leaderboard_rank(_user_id uuid, _rank integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_set_pause(_paused boolean, _message text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_set_pin(_pin text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_set_reward_distribution(_tid uuid, _first_pct numeric, _second_pct numeric, _third_pct numeric, _platform_pct numeric) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_set_user_banned(_user_id uuid, _banned boolean) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_set_user_status(_user_id uuid, _status text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_start_domino_tournament(_tid uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_stats_daily(_days integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_suspend_player(_uid uuid, _hours integer, _reason text, _add_warning boolean) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_top_referrers() FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_tournament_add_bots(_tid uuid, _count integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_tournament_cancel(_tid uuid, _reason text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_tournament_create(_name text, _game_slug text, _format text, _players_per_match integer, _max_players integer, _entry_fee_ar numeric, _admin_prize_pool_ar numeric, _winners_count integer, _p1 numeric, _p2 numeric, _p3 numeric, _pool_size integer, _qualifiers_per_pool integer, _max_concurrent integer, _lobby_minutes integer, _description text, _registration_closes_at timestamp with time zone, _starts_at timestamp with time zone) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_tournament_delete(_tid uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_tournament_force_winner(_match_id uuid, _entrant_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_tournament_next_stage(_tid uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_tournament_set_auto(_tid uuid, _auto boolean) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_tournament_set_status(_tid uuid, _status text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_tournament_simulate(_tid uuid, _max_steps integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_tournament_simulate_new(_game_slug text, _format text, _players integer, _players_per_match integer, _pool_size integer, _qualifiers_per_pool integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_tournament_start(_tid uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_update_bot(_participant_id uuid, _intelligence integer, _win_bias integer) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_update_bug_report(_id uuid, _status text, _admin_note text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_update_cms_content(_key text, _content jsonb) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_update_community(_room_id uuid, _name text, _image_url text, _enabled boolean) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_update_referral_settings(_enabled boolean, _stake_commission_pct numeric, _stake_commission_max_matches integer, _require_phone boolean, _max_daily integer, _auto_flag_velocity integer, _campaign_label text, _campaign_expires timestamp with time zone, _campaign_bonus_pct numeric) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_update_settings(_admin_phone text, _admin_label text, _signup_bonus numeric, _referral_pct numeric, _game_commission_pct numeric, _min_deposit numeric, _min_withdraw numeric, _mvola_phone text, _mvola_name text, _orange_phone text, _orange_name text, _airtel_phone text, _airtel_name text, _withdrawal_fee_pct numeric) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_user_history(_user_id uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_validate_round(_tid uuid) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_validate_session(_fingerprint text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_verify_email_otp(_code text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_verify_phone(_user_id uuid, _approve boolean) FROM anon;
REVOKE EXECUTE ON FUNCTION public.admin_verify_pin(_pin text) FROM anon;

-- ═══ FIX: fanorona_create — enforce commission BETWEEN 0 AND 100 ═══
CREATE OR REPLACE FUNCTION public.fanorona_create(_stake numeric, _private boolean, _commission numeric DEFAULT 10)
 RETURNS uuid
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path = 'public'
AS $function$
DECLARE
  v_uid uuid := auth.uid();
  v_balance numeric;
  v_code text;
  v_id uuid;
  v_name text;
BEGIN
  IF v_uid IS NULL THEN RAISE EXCEPTION 'auth required'; END IF;
  IF _stake < 0 THEN RAISE EXCEPTION 'invalid stake'; END IF;
  -- SECURITY: enforce commission between 0 and 50 (max 50%)
  IF _commission IS NULL OR _commission < 0 OR _commission > 50 THEN
    RAISE EXCEPTION 'invalid commission';
  END IF;
  SELECT balance_ar, pseudo INTO v_balance, v_name FROM public.profiles WHERE id = v_uid;
  IF v_balance < _stake THEN RAISE EXCEPTION 'insufficient balance'; END IF;
  IF _private THEN v_code := upper(substring(md5(random()::text||clock_timestamp()::text) from 1 for 6)); END IF;

  INSERT INTO public.fanorona_games(host_id, stake, pot, commission_pct, is_private, room_code, state)
  VALUES (v_uid, _stake, _stake, _commission, _private, v_code,
    jsonb_build_object('phase','waiting','board', public._fanorona_init_board(), 'chain_from', null, 'chain_dirs', '[]'::jsonb))
  RETURNING id INTO v_id;

  UPDATE public.profiles SET balance_ar = balance_ar - _stake WHERE id = v_uid;
  INSERT INTO public.transactions(user_id, type, amount, ref_id, note) VALUES (v_uid, 'fanorona_stake', -_stake, v_id, 'Create fanorona');
  INSERT INTO public.fanorona_participants(game_id, user_id, slot, color, display_name) VALUES (v_id, v_uid, 0, 'white', COALESCE(v_name,'Player'));
  RETURN v_id;
END $function$;

REVOKE EXECUTE ON FUNCTION public.fanorona_create(numeric, boolean, numeric) FROM anon;
GRANT EXECUTE ON FUNCTION public.fanorona_create(numeric, boolean, numeric) TO authenticated;

-- ═══ Enable RLS on ludo_games (was disabled!) ═══
ALTER TABLE public.ludo_games ENABLE ROW LEVEL SECURITY;
