ALTER TABLE public.chess_games ADD COLUMN IF NOT EXISTS pause_used BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE public.fanorona_games ADD COLUMN IF NOT EXISTS pause_used BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE public.domino_games ADD COLUMN IF NOT EXISTS pause_used BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE public.rami_games ADD COLUMN IF NOT EXISTS pause_used BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE public.poker_games ADD COLUMN IF NOT EXISTS pause_used BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE public.ludo_games ADD COLUMN IF NOT EXISTS pause_used BOOLEAN NOT NULL DEFAULT FALSE;